swagger: "2.0"
info:
  description: "Simple API to manage tasks"
  version: "1.0.0"
  title: "tasks API"
host: "localhost:3000"
basePath: "/"
consumes:
- "application/json"
produces:
- "application/json"
tags:
- name: "task"
  description: "operations on tasks"
paths: 
responses:
  notFound:
    description: Not found
    schema:
      $ref: '#/definitions/genericError'
  unprocessableEntity:
    description: The provided data is not valid
    schema:
      $ref: '#/definitions/genericError'

definitions:
  genericError:
    type: 'object'
    properties: 
      errorMessage: 
        type: "string"
      errorDetails: 
        type: "object"