swagger: "2.0"
info:
  description: "Simple API to manage tasks"
  version: "1.0.0"
  title: "tasks API"
host: "localhost:3000"
basePath: "/"
consumes:
- "application/json"
produces:
- "application/json"
tags:
- name: "task"
  description: "operations on tasks"
paths:
  /tasks:
    get:
      tags:
      - "task"
      summary: "Get a list of tasks"
      description: ""
      responses:
        "200":
          description: "Everything went well"
          schema:
            type: 'object'
            properties:
              data:
                type: 'array'
                items: 
                  $ref: '#/definitions/tasksimplified'
    post:
      tags:
      - "task"
      summary: "Add a new task"
      description: ""
      parameters:
      - in: "body"
        name: "task"
        description: "task object that needs to be added in DB"
        required: true
        schema:
          allOf:
           - $ref: "#/definitions/taskEditableAttributes"
           - type: 'object'
             required:
              - "email"
      responses:
        "201":
          description: "Created"
          schema:
            type: "object"
            properties:
              data:
                $ref: "#/definitions/task"
        "400":
          description: "Invalid input. The task object provided is not valid"
          schema:
            type: 'object'
            properties:
              errorMessage:
                type: "string"
          
  /tasks/{taskId}:
    get:
      tags:
      - "task"
      summary: "Find a task by ID"
      description: "Returns a single task"
      parameters:
      - name: "taskId"
        in: "path"
        description: "ID of task to return"
        required: true
        type: "integer"
        format: "int64"
      responses:
        "200":
          description: "successful operation"
          schema:
            type: 'object'
            properties:
              data:
                type: "object"
                $ref: "#/definitions/task"
        "404":
          description: "task not found"
    put:
      tags:
      - "task"
      summary: "Update an existing task"
      description: ""
      parameters:
      - name: "taskId"
        in: "path"
        description: "ID of task to return"
        required: true
        type: "integer"
        format: "int64"
      - in: "body"
        name: "task"
        description: "task object that needs to be updated"
        required: true
        schema:
          $ref: "#/definitions/taskEditableAttributes"
      responses:
        "200":
          description: "Updated"
          schema:
            type: "object"
            properties:
              data:
                $ref: "#/definitions/task"
        "404":
          description: "task not found"
        "400":
          description: "Invalid input. The task object provided is not valid"
          schema:
            type: 'object'
            properties:
              errorMessage:
                type: "string"
    delete:
      tags:
      - "task"
      summary: "Deletes a task"
      description: ""
      parameters:
      - name: "taskId"
        in: "path"
        description: "task id to delete"
        required: true
        type: "integer"
        format: "int64"
      responses:
        "404":
          description: "task not found"
        "200":
          description: "OK"
definitions:
  taskEditableAttributes:
    type: "object"
    properties:
      first_name:
        type: "string"
        example: "John"
      last_name:
        type: "string"
        example: "Doe"
      email: 
        type: "string"
        example: "john.doe@gmail.com"
      active: 
        type: "boolean"
      
  tasksimplified:
    type: "object"
    properties:
      id:
        type: "integer"
        format: "int64"
      name:
        type: "string"
        example: "John"
      email: 
        type: "string"
        example: "john.doe@gmail.com"
      active: 
        type: "boolean"
      
  task:
    allOf: 
      - type: "object"
        properties:
          id:
            type: "integer"
            format: "int64"
      - $ref: '#/definitions/taskEditableAttributes'
      